Kiosk.StackOverFlowTask/Models/QuestionVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace Kiosk.StackOverFlowTask.Models
{
    public class QuestionVM
    {   
        [Display(Name = "Question Id")]
        public int Question_Id { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }       
        [Display(Name = "Creation Date")]
        public DateTime Creation_Date { get; set; }
        [Display(Name = "Last Activity Date")]
        public DateTime Last_Activity_Date { get; set; }
        public float Score { get; set; }
        public String Tags { get; set; }
    }
}

Kiosk.StackOverFlowTask/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kiosk.StackOverFlowTask.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Kiosk.StackOverFlowTask/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kiosk.StackOverFlow.Model;
using PagedList;
using AutoMapper;
using Kiosk.StackOverFlowTask.Models;
using Kiosk.StackOverFlow.SharedFeatures;
using Kiosk.StackOverFlow.Business.Questions;

namespace Kiosk.StackOverFlowTask.Controllers
{
    public class QuestionController : Controller
    {
        private string _QuestionsUrl;
        private string _QuestionUrl;
        public QuestionController()
        {
             _QuestionsUrl = HttpUtility.HtmlDecode(CommonMethods.GetAppSettingsValue("StackOverFlowApiQuestionsListUrl"));
             _QuestionUrl = HttpUtility.HtmlDecode(CommonMethods.GetAppSettingsValue("StackOverFlowApiQuestionByIdUrl"));            
        }
        // GET: Question
        public ActionResult Index(int? page)
        {
            var pageIndex = page.HasValue ? page.Value : 1;
            var pageSize = Convert.ToInt32(CommonMethods.GetAppSettingsValue(Strings.PageSize));

            QuestionService service = new QuestionService(_QuestionsUrl, _QuestionUrl);
            var questionsDto = service.GetQuestionsList(pageIndex ,100);
            var questionsVM = Mapper.Map<List<QuestionDTO>, List<QuestionVM>>(questionsDto);

            return View(questionsVM.ToPagedList(pageIndex, pageSize));
        }

        public ActionResult Details(int Id)
        {
            QuestionService service = new QuestionService(_QuestionsUrl, _QuestionUrl);
            var questionDetailsDto = service.GetQuestionById(Id);
            var questionDetailsVM = Mapper.Map<QuestionDTO, Models.QuestionVM>(questionDetailsDto);

            return View(questionDetailsVM);
        }
    }
}

Kiosk.StackOverFlowTask/Views/Question/Details.cshtml
@model Kiosk.StackOverFlowTask.Models.QuestionVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Question Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Question_Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question_Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model=> model.Link)
        </dt>

        <dd>
            <a href="@Model.Link">@Model.Link</a>Documents\Source\Repos
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Creation_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Creation_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Last_Activity_Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Last_Activity_Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

    </dl>
</div>
<p>   
    @Html.ActionLink("Back to List", "Index")
</p>

Kiosk.StackOverFlowTask/Views/Question/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@using Kiosk.StackOverFlowTask.Models
@model PagedList.IPagedList<QuestionVM>

<style>
    .ul.pagination {
        display: inline-block;
        padding: 0;
        margin: 0;
    }

    ul.pagination li {
        display: inline;
    }

        ul.pagination li a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
        }

            ul.pagination li a.active {
                background-color: #4CAF50;
                color: white;
            }

            ul.pagination li a:hover:not(.active) {
                background-color: #ddd;
            }
</style>

    @{
        ViewBag.Title = "Index";
    }

    <h2>Questions List</h2>

<form>
    <table class="table">
        <tr>
            <th>
                @Kiosk.StackOverFlowTask.Strings.Title
            </th>
            <th>
                @Kiosk.StackOverFlowTask.Strings.Score
            </th>
            <th>
                @Kiosk.StackOverFlowTask.Strings.Creation_Date
            </th>
            <th>
                @Kiosk.StackOverFlowTask.Strings.Last_Activity_Date
            </th>
            <th>

            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Score)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Creation_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Last_Activity_Date)
                </td>

                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Question_Id }, new { target = "_blank" })
                </td>
            </tr>
        }

    </table>

    <div id="container" style="margin-left: 20px">
        <p></p>
        <p></p>
        <div class="pagination" style="margin-left: 400px">
            Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            of @Model.PageCount   @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
        </div>        
    </div>
    <input type="submit" class="btn btn-primary" value="Refresh" />
</form>

Kiosk.StackOverFlowTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Stackoverflow", "Index", "Question", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Question")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>